[project]
name = "aiogramui"
version = "1.1.4"
description = "A minimalistic UI framework for aiogram bots."
readme = "README.md"
license = { text = "MIT" }
authors = [
    { name="evryoneowo", email="evryhvh@email.com" }
]
requires-python = ">=3.9"
dependencies = [
    "aiogram>=3.0.0"
]

[project.urls]
Homepage = "https://github.com/evryoneowo/aiogramui"
Repository = "https://github.com/evryoneowo/aiogramui"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"